excluded:
  - ./**Tests
  - Pods
  - vendor
  - scripts
  - Templates
  - fastlane

line_length:
  warning: 180
  error: 360
  ignores_comments: true
opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - for_where
  - identical_operands
  - implicit_getter
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - operator_usage_whitespace
  - override_in_extension
  - sorted_first_last
  - custom_rules
disabled_rules:
  - type_name
  - identifier_name
  - nesting