# This is a basic workflow to help you get started with Actions

name: run-tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    env:
      MINT_PATH: mint/lib
      MINT_LINK_PATH: mint/bin

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_13.0.app/Contents/Developer'

    - name: Cache Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Cache Mint packages
      uses: actions/cache@v2
      with:
        path: mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-

    - name: Cache libraries via SwiftPM
      uses: actions/cache@v2
      with:
        path: SourcePackages
        key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/UhooiPicBook.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swiftpm-
    
    - name: Configure Project
      run: |
        ./scripts/setup.sh
        ./scripts/bootstrap.sh

    - name: Run test
      run: bundle exec fastlane test

