name: World
on:
  workflow_call:

jobs:
  world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: labels
        shell: bash
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          json=$(gh pr view "$PR_NUMBER" --json labels | jq -c '.labels|map(.name)')
          echo "json=$json" >> "$GITHUB_OUTPUT"
      - name: Echo Label
        run: echo "${{steps.labels.outputs.json}}"
      - if: contains(fromJSON(steps.labels.outputs.json), 'iOS')
        run: echo "World"
