name: World
on:
  workflow_call:
  workflow_run:
    workflows:
      - Hello
    types:
      - completed

jobs:
  world:
    # if: contains(fromJSON(steps.labels.outputs.json), 'iOS')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "World"
